version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projectexpress0/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 1800
      runas: ubuntu